### ISSUE TITLE
problem with links given by twitter API when collecting tweet metadata

### ISSUE THREAD

**Issue by ameliepelle** [medialab/twitwi#27]
tweet with id 1430825154007945223 (https://twitter.com/i/web/status/1430825154007945223) : links not available in extended_entities, API gives back a link to the tweet and not the link shared by the twitter user
tweet with id 1376660135024721925 (https://twitter.com/TwitterBusiness/status/1376660135024721925) : no link available in extended_entities where there should be a link to the twitter website (shared in the tweet)
Other tweets like this one : https://twitter.com/JournalDuGeek/status/1438518441023983616 don't have this problem.
twitwi doesn't have a functionality go around this

**Comment by boogheta** [comment]
Hello @ameliepelle I'm not sure I understand what you mean exactly but it seems to me like your problem comes from the missing tweet_mode argument in your API calls.
It is not well documented by Twitter, but you should most of the time add the following arguments to Twitter v1 API calls:
```include_entities="true", tweet_mode="extended"`
For instance if I call:
```
t = Twitter(auth=OAuth(....))
t.statuses.show(_id="1430825154007945223", include_entities="true", tweet_mode="extended")
```
There I get an entities field which contains within urls the desired link instead of the i/web/status one.
This is a legacy thing coming from when they passed the limit from 140 characters to 280. After that time, tweets longer than 140 characters are truncated (and there is a truncated: True field indicating this) and the entities then contain a link to the full tweet rather than the links within it.
